# Day 17


# NUMPY


- Time taken by list is slower while the numpy is faster as it is very easy and state forward.
- Array stores only those elements which are of single datatypes with multiple elements.
- But in numpy we can store multiple datatypes as well as multiple data files.
- We use numpy for much optimizatio to act faster.
- Whenever we say arry the object of the perticulat array is known as list, Same way we are dealing withe the numpy lib we say ndarray.

In [8]:
import numpy as np
import time

In [9]:
a = np.random.rand(100000000)

# It creates the random values of 0 and 1 till those numbers like binary code.

In [10]:
# List

start = time.time()
mean_list = sum(a)/len(a)
print (time.time()-start)

7.814604997634888


In [11]:
# Numpy 

start = time.time()
mean_np = np.mean(a)
print (time.time()-start)

0.1171870231628418


In [12]:
np.__version__

'1.24.1'

# OPERATIONs

## Initializing the NumPy Array

In [13]:
# Synatx
# arr = np.array()

In [14]:
# 0-D (Zero Dimensional)
arr = np.array(4)
arr

array(4)

In [15]:
# 1-D (One Dimensional)
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# 2-D (TWo Dimensional)
arr = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
# 3-D (Three Dimensional)
arr = np.array([
    [
        [1,2,3,4,5],
     [6,7,8,9,10]
    ],
    [
        [11,12,13,14,15],
     [11,12,13,14,15]
    ]
])
arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [11, 12, 13, 14, 15]]])

## ndim attribute --> It will gonna return the dimensions of the array.

In [18]:
# 0-D (Zero Dimensional)
arr = np.array(4)
arr.ndim

0

In [19]:
# 1-D (One Dimensional)
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr.ndim

1

In [20]:
# 2-D (TWo Dimensional)
arr = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13,14,15]])
arr.ndim

2

In [21]:
# 3-D (Three Dimensional)
arr = np.array([
    [
        [1,2,3,4,5],
     [6,7,8,9,10]
    ],
    [
        [11,12,13,14,15],
     [11,12,13,14,15]
    ]
])
arr.ndim

3

## ndmin ( ) --> Converting 1-D array into any other Dimension.

In [22]:
# IF we want to convert one dimensional array into any other dimensional array we can use ndmin function.
# 1-D (One Dimensional)
arr = np.array([1,2,3,4,5,6,7,8,9,10],ndmin = 7)
arr

array([[[[[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]]]]]])

In [23]:
arr.ndim

7

## Shape --->  IT tells about then size of elements.

In [24]:
# 2-D (Two Dimensional)
arr = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13,14,15]])
arr.shape

(3, 5)

In [25]:
# 3-D (Three Dimensional)
arr = np.array([
    [
        [1,2,3,4,5],
     [6,7,8,9,10]
    ],
    [
        [11,12,13,14,15],
     [11,12,13,14,15]
    ]
],ndmin = 10)
arr.shape


(1, 1, 1, 1, 1, 1, 1, 2, 2, 5)

## dtypes

In [26]:
arr.dtype

dtype('int32')

In [27]:
arr = np.array(['apple', 'mangoes', 'cherry', 9.9])
arr.dtype

# U stands for Unicode
# I --> Integer
# S --> String
# B --> Boolean
# C --> Complex
# F --> Float

dtype('<U32')

## size - Total numbers of elements in the data.

In [28]:
arr.size  # this is attribute

4

In [29]:
# np.size(ndarry,1 (row), 0 (column) ) ## this the the function 

In [30]:
# 3-D (Three Dimensional)
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [11,12,13,14,15]
    
])
arr.size

20

In [31]:
np.size(arr,0)

4

## Itemsize - It tells us about the length of the single element in the bytes.

In [32]:
arr.itemsize

4

## nbytes --> Total bytes



In [33]:
arr.nbytes

80

# Day 18

# CRUD Operators

In [34]:
import numpy as np 

## C - Create

In [35]:
arr = np.array ([[1,2,3],[4,5,6]])
arr.ndim

2

In [ ]:
# np.zerose() it will create all the elements with zero elements

arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#  np.ones() it will create all the elements with 1 elements

arr = np.ones((5,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
#  np.empty() it will get filled up with the random values.

arr = np.empty((4,5))
arr

array([[1.20708497e-311, 6.95182276e-310, 1.20708497e-311,
        6.95182276e-310, 1.20708496e-311],
       [6.95182276e-310, 1.20708496e-311, 6.95182276e-310,
        1.20708496e-311, 6.95182276e-310],
       [1.20708496e-311, 6.95182276e-310, 1.20708496e-311,
        6.95182276e-310, 1.20708496e-311],
       [6.95182276e-310, 1.20708496e-311, 6.95182276e-310,
        1.20708496e-311, 6.95182276e-310]])

In [38]:
# np.full()

arr = np.full([3,4,5],19)
arr

array([[[19, 19, 19, 19, 19],
        [19, 19, 19, 19, 19],
        [19, 19, 19, 19, 19],
        [19, 19, 19, 19, 19]],

       [[19, 19, 19, 19, 19],
        [19, 19, 19, 19, 19],
        [19, 19, 19, 19, 19],
        [19, 19, 19, 19, 19]],

       [[19, 19, 19, 19, 19],
        [19, 19, 19, 19, 19],
        [19, 19, 19, 19, 19],
        [19, 19, 19, 19, 19]]])

In [39]:
# np.eye() --> Identity Matrix
# In identity matrix no of rows and column are same.

arr = np.eye(2)
arr 

array([[1., 0.],
       [0., 1.]])

In [40]:
# np.diag()

arr = np.diag([10,20,30,40,50,60,70,80,90])
arr

array([[10,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 30,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 40,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 50,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 60,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 70,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 80,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 90]])

In [41]:
# np.linspace() --->
# 10 to 100 give 10 elements

arr = np.linspace(10,100,10) 
arr

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [42]:
# np.random.rand()

arr = np.random.rand(10)
arr

array([0.82958535, 0.44646171, 0.3753689 , 0.05123938, 0.37398765,
       0.43824047, 0.39580656, 0.01423181, 0.77861904, 0.39006833])

In [43]:
arr = np.random.randint(19,30, size = (3,4))
arr

array([[25, 19, 20, 22],
       [27, 23, 28, 26],
       [25, 24, 29, 27]])

In [44]:
# np.arange()

arr = np.arange(1,12,2)
arr

array([ 1,  3,  5,  7,  9, 11])

# U --> Update

In [47]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])
arr3 = np.array([
    [
      [1,2,3],
     [4,5,6]],[
         [7,8,9],
         [11,12,13]
     ]
])

print(arr1) 
print("\n", arr2)
print('\n This is 3-D \n\n',arr3)

[1 2 3 4 5]

 [[1 2 3 4]
 [5 6 7 8]
 [1 3 5 7]]

 This is 3-D 

 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]


In [48]:
# Indexing
 
#  1-D Array
print(arr1[-1], arr1[3])

# 2-D Array
# arr[row:column]
print(arr2 [2,3])

# 3-D Array
print(arr3[0,1,1])

# updating the value in matrix
arr3[0,1,1] = 19
print(arr3)

5 4
7
5
[[[ 1  2  3]
  [ 4 19  6]]

 [[ 7  8  9]
  [11 12 13]]]


In [49]:
# Slicing --> Accessing the certain data of the files.
arr2
arr2[1:]

array([[5, 6, 7, 8],
       [1, 3, 5, 7]])

In [50]:
arr3

array([[[ 1,  2,  3],
        [ 4, 19,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [52]:
# arr3[0,1,0:2]
arr3[0,1][0:2]

array([ 4, 19])

In [53]:
# reshape
# Quiz 

# Create a matrix 3x4,10 to 500 + elements should be evenly distributed.

mat =  np.linspace(10,500,12)
mat.reshape(3,4)

# element(12) % n-dimentsion == 0

array([[ 10.        ,  54.54545455,  99.09090909, 143.63636364],
       [188.18181818, 232.72727273, 277.27272727, 321.81818182],
       [366.36363636, 410.90909091, 455.45454545, 500.        ]])

In [ ]:
#  Create a 7x9 matrix where all the elements are rondom

# ra = np.random.rand(63).reshape(7,9)
# ra

ra = np.random.randint (100, size =(7,9))
ra

array([[61, 73, 71, 52, 30, 45, 59, 33, 16],
       [32, 37,  4, 14, 40, 90, 54, 15, 98],
       [57, 27, 18, 54, 59, 83, 72, 93, 79],
       [50, 19, 29, 62, 28, 23, 80, 83, 45],
       [21,  9, 69, 92, 56, 87, 63, 23, 87],
       [61,  2, 76, 26, 92, 14, 18, 53, 37],
       [27, 56, 98, 38, 88, 32, 83, 79, 95]])

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [ ]:
arr2d = np.array([15,16,17,18])
arr2dd = np.array([15,16,17,18])

In [ ]:
# Adding to array

np.append([arr2d], [arr2dd], axis=0)

array([[15, 16, 17, 18],
       [15, 16, 17, 18]])

# Day 19

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([ [3,6,9,], [12,15,18]])
arr2 = np.array([[24,20,16],[12,8,4]])

In [ ]:
arr1

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
arr2

array([[24, 20, 16],
       [12,  8,  4]])

# Mathematical Functions and Stats

## Addition --> Add two matrices or add and element to a matrix.

In [ ]:
# Adding two matrics
arr1 + arr2

array([[27, 26, 25],
       [24, 23, 22]])

In [ ]:
# Adding an element

arr2 + 19

array([[43, 39, 35],
       [31, 27, 23]])

In [ ]:
arr3 = np.array([1,10,19])
arr2 + arr3

array([[25, 30, 35],
       [13, 18, 23]])

## Subtraction

In [ ]:
print(arr1)
print("\n", arr2)

[[ 3  6  9]
 [12 15 18]]

 [[24 20 16]
 [12  8  4]]


In [ ]:
arr1 - arr2

array([[-21, -14,  -7],
       [  0,   7,  14]])

In [ ]:
arr1 - 100

array([[-97, -94, -91],
       [-88, -85, -82]])

## Division

In [ ]:
arr1 / arr2

array([[0.125 , 0.3   , 0.5625],
       [1.    , 1.875 , 4.5   ]])

In [ ]:
arr1 / arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
 arr1 / 4

array([[0.75, 1.5 , 2.25],
       [3.  , 3.75, 4.5 ]])

## Exponential

In [ ]:
arr1 ** arr2

array([[    282429536481, 3656158440062976, 1853020188851841],
       [   8916100448256,       2562890625,           104976]])

In [ ]:
arr1 ** 2

array([[  9,  36,  81],
       [144, 225, 324]])

## Multiplication --> Cross and Dot

In [ ]:
print(arr1)
print ("\n")
print (arr2)

[[ 3  6  9]
 [12 15 18]]


[[24 20 16]
 [12  8  4]]


In [ ]:
# Cross Product

arr1 * arr2

array([[ 72, 120, 144],
       [144, 120,  72]])

In [ ]:
# Dot product

arr3 = np.array([[1,2],[3,4],[5,6]])
arr3.ndim

2

In [ ]:
arr3.shape

(3, 2)

In [ ]:
arr1.shape

(2, 3)

In [ ]:
# Step1
# np.dot(arr1,arr3)
np.dot(arr3,arr1)

array([[ 27,  36,  45],
       [ 57,  78,  99],
       [ 87, 120, 153]])

In [ ]:
# Step2
np.matmul(arr1,arr3)

# np.matmul(arr3,arr1)

array([[ 66,  84],
       [147, 192]])

# Determinant

* Square matrix --> No. of rows = No. of columns.
* No of rows and no. of columns = Same

* The output of determinant can be  positive and negative.


In [ ]:
detarray = np.array([[-4,-10],[0,5]])
detarray.ndim

2

In [ ]:
# np.linalg.det(arr)

np.linalg.det(detarray)

-19.999999999999996

In [ ]:
darray = np.array([[-4,-10,-6],[0,5,7],[-9,6,0]])
np.linalg.det(darray)

528.0

## Inverse of Matrix:

In [ ]:
arrinv = np.array([[3,4], [7,8]])
arrinv

array([[3, 4],
       [7, 8]])

In [ ]:
np.linalg.inv(arrinv)

array([[-2.  ,  1.  ],
       [ 1.75, -0.75]])

In [ ]:
# Inverse = (1/det(mat)) * transpose(Cofactorial of the matrix)

deter = np.linalg.det(arrinv) 
deter

-4.000000000000001

In [ ]:
newdet = 1 / deter
newdet

-0.24999999999999994

In [ ]:
# Adjoint of matrix --> we have to find the cofactor of the matrix.

np.linalg.inv(arrinv)

array([[-2.  ,  1.  ],
       [ 1.75, -0.75]])

In [ ]:
arrinv

array([[3, 4],
       [7, 8]])

In [ ]:
arrinv.transpose()

array([[3, 7],
       [4, 8]])

## Reciprocal

In [ ]:
arreci = np.array([[10,20],[30,40]],dtype = 'float')
arreci

array([[10., 20.],
       [30., 40.]])

In [ ]:
# np.reciprocal(array_name)

np.reciprocal((arreci))

array([[0.1       , 0.05      ],
       [0.03333333, 0.025     ]])

# Statistics

In [54]:
statarr = np.array([[20,50,-40],[9,10,-1],[7,26,32]])
print(statarr.ndim)
print('\n')
print(statarr.shape)
print('\n')
print (statarr)

2


(3, 3)


[[ 20  50 -40]
 [  9  10  -1]
 [  7  26  32]]


## max()

In [55]:
np.max(statarr)

50

In [56]:
# If we give (axix= 0 col, 1 = row) then it will print out all the max values of each  column.

print(np.max(statarr,axis = 0))
print("\n")
print(np.max(statarr,axis = 1))

[20 50 32]


[50 10 32]


##  min()

In [57]:
print (np.min(statarr))
print ('\n')
print(np.min(statarr,axis = 0))
print('\n')
print(np.min(statarr,axis = 1))

-40


[  7  10 -40]


[-40  -1   7]


##  Sum

In [58]:
statarr

array([[ 20,  50, -40],
       [  9,  10,  -1],
       [  7,  26,  32]])

In [59]:
np.sum(statarr)

113

In [60]:
np.sum(statarr,axis =0)

array([36, 86, -9])

In [61]:
np.sum(statarr,axis =1)

array([30, 18, 65])

## argmax( ) --> It will give the INDEX POSITION of the maximum element. 

In [62]:
statarr

array([[ 20,  50, -40],
       [  9,  10,  -1],
       [  7,  26,  32]])

In [63]:
np.argmax(statarr)

1

In [64]:
statarr[2,1] = 100
statarr[1,1] = -100
statarr

array([[  20,   50,  -40],
       [   9, -100,   -1],
       [   7,  100,   32]])

In [ ]:
np.argmax(statarr,axis = 1)

array([1, 0, 1])

In [ ]:
np.argmax(statarr,axis = 0)

array([0, 2, 2])

## argmin( )

In [ ]:
statarr

array([[  20,   50,  -40],
       [   9, -100,   -1],
       [   7,  100,   32]])

In [ ]:
np.argmin(statarr)

4

In [ ]:
np.argmin(statarr,axis = 0)

array([2, 1, 0])

In [ ]:
np.argmin(statarr,axis = 1)

array([2, 1, 0])

## around( ) --> it will round up the values to the nearest value

In [65]:
arr_ = np.array([3.501,0.98])

In [66]:
np.around(arr_,decimals = 2)

array([3.5 , 0.98])

## floor (lowest nearest integer) & ceil (uppere nearest integer)

- Ceiling is the upward direction  
- Floor is in the downward direction
- It round of the values in the int 

In [ ]:
a = np.array([-1.7, -4.2, 4.6, -0.87, 4.9])
a

array([-1.7 , -4.2 ,  4.6 , -0.87,  4.9 ])

In [ ]:
np.floor(a)

array([-2., -5.,  4., -1.,  4.])

In [ ]:
np.ceil(a)

array([-1., -4.,  5., -0.])

## copy (copy the original file and won'y get reflected in the copy file) 
## view (the changes will be reflected in the original file)

In [ ]:
a

array([-1.7 , -4.2 ,  4.6 , -0.87])

In [ ]:
# copy
x = a.copy()

In [ ]:
x[0] = 10
x

array([10.  , -4.2 ,  4.6 , -0.87])

In [ ]:
a

array([-1.7 , -4.2 ,  4.6 , -0.87])

In [ ]:
# view
y = a.view()

In [ ]:
y[1] = 5
y

array([-1.7 ,  5.  ,  4.6 , -0.87])

In [ ]:
a

array([-1.7 ,  5.  ,  4.6 , -0.87])

## Iteration


In [ ]:
a

array([-1.7 , -4.2 ,  4.6 , -0.87])

In [ ]:
for i in a:
  print (i)

-1.7
-4.2
4.6
-0.87


In [ ]:
for i in arr1:
  print (i)

[3 6 9]
[12 15 18]


In [ ]:
for i in arr1:
  for j in i :
    print (j)

3
6
9
12
15
18


In [ ]:
for i in np.nditer(arr1):
  print (i)

3
6
9
12
15
18


In [ ]:
for i in np.nditer(arr1[1:]):
  print (i)

12
15
18


# Day 20

## More on NumPy

In [67]:
import numpy as np

In [68]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,12,13],[14,15,16]])

print(arr1)
print('\n')
print(arr2)

[[1 2 3]
 [4 5 6]]


[[11 12 13]
 [14 15 16]]


## Stacking --> It means to joins to get more array. 

- vertical (vstack)-- one below the other
- horizontal (hstack)-- right hand side of another.

In [69]:
np.vstack((arr1,arr2,arr1,arr1)) # we can go with () and []

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [ ]:
np.hstack ([arr1,arr2])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [ ]:
arr3 = np.array ([100,200,300])

In [ ]:
np.vstack((arr1,arr3)) 
# While performing the vstack the no. of columns should = both the arrays

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300]])

In [ ]:
# np.hstack((arr1,arr3)) 

#  as the arr3 dimension != arr1 dimension so we will get the error 
# While performing the hstack the no. of rows should = both the arrays

In [ ]:
print (f'arr3 = {arr3}','\n')
arr4 = np.array([500,600,700])
arr4

arr3 = [100 200 300] 



array([500, 600, 700])

### dstack --> It will stack along with the height.
* The rows changes to columns.
* Both the array should have same shape.

In [ ]:
np.dstack([arr3,arr4])

array([[[100, 500],
        [200, 600],
        [300, 700]]])

## spliting --> breaking one array into two or more array.

* array_split ( )

In [ ]:
arr3


array([100, 200, 300])

In [ ]:
br = np.array_split(arr3,3)
br

[array([100]), array([200]), array([300]), array([], dtype=int64)]

In [ ]:
br [0], br[2]

(array([100]), array([300]))

In [ ]:
# If the array have less no than splitting then it will adjust accordingly.
br = np.array_split(arr3,10)
br

[array([100]),
 array([200]),
 array([300]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64)]

## searching
* function of searching is where( )

In [ ]:
newarr = np.array([1,2,3,4,5,4,4])
newarr

array([1, 2, 3, 4, 5, 4, 4])

In [ ]:
np.where(newarr == 4)

# It will return all the index values where it matches 4.

(array([3, 5, 6]),)

## sorting

In [ ]:
newarr = np.array([10,5,6,-10,-7,20,0,4,18,4.6])
newarr

array([ 10. ,   5. ,   6. , -10. ,  -7. ,  20. ,   0. ,   4. ,  18. ,
         4.6])

In [ ]:
np.sort(newarr) #ascending

array([-10. ,  -7. ,   0. ,   4. ,   4.6,   5. ,   6. ,  10. ,  18. ,
        20. ])

In [ ]:
-np.sort(-newarr) #descending

array([ 20. ,  18. ,  10. ,   6. ,   5. ,   4.6,   4. ,   0. ,  -7. ,
       -10. ])

## any ( ) & all ( )

## any ( ) -- will return TRUE if any condition satisfy
## all ( ) -- only will return TRUE if all the condition satisfy or else it will return FALSE.

In [80]:
newarr = np.array([2,4,6,8,9,10])
newarr

array([ 2,  4,  6,  8,  9, 10])

In [ ]:
np.any(newarr % 2 == 0) 

True

In [ ]:
np.all(newarr % 2 == 0)

False

## resize ( )

In [72]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
np.reshape(a,(3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
np.resize(a,(3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2]])

In [75]:
 np.resize(a,(10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9, 10, 11,  0,  1],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3]])

## delete

In [ ]:
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# delete (arr, obj, axis)
np.delete(a,5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [ ]:
delmat = np.array([[1,2,3],[4,3,6]])
delmat

array([[1, 2, 3],
       [4, 3, 6]])

In [ ]:
np.delete(delmat,3)

array([1, 2, 3, 3, 6])

In [ ]:
np.delete(delmat,1,axis=0)

array([[1, 2, 3]])

## LCM

* lcm (arry_name1, arry_name2)
if there are more than 2 array or we have to find out the LCM of matrix then we have to use the **reduce** function.

In [ ]:
num1 = 25
num2 = 125
num3 = 625

np.lcm.reduce((num2,num3,num1))

625

In [ ]:
newarr

array([ 2,  4,  6,  8,  9, 10])

In [ ]:
np.lcm.reduce(newarr)

360

## GCD (Gretest common Denominator)

* np.gcd( )

In [ ]:
a = 16
b = 32
 
np.gcd(a,b)

16

In [ ]:
c = 64

np.gcd.reduce ((a,b,c))

16

## Linear Equation

* np.linalg.solve( )

In [ ]:
# 3x + y = 9
# x + 2y = 8

In [ ]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])

print (a,'\n','\n',b)

[[3 1]
 [1 2]] 
 
 [9 8]


In [ ]:
np.linalg.solve(a,b)

array([2., 3.])

## Quadrictic Equations

* np.roots ( )

In [ ]:
# x^2 + 4x = -4
# x^2 + 4x + 4 = 0

In [ ]:
coeff = np.array([1,4,4])

In [ ]:
np.roots(coeff)

array([-2., -2.])

## vdot ( ) --> Vectordot


In [ ]:
a = np.array([[1,2,3,],[4,5,6]])
b = np.array([[10,20,30,],[40,50,60]])

#  1*10 + 2*28 +.... + 6*60

In [ ]:
np.vdot(a,b)

910

## mean ( )

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.mean(a)

3.5

### varaience is the square of the perticular sd

## Weighted Mean

- First it well get multiplyed with each of their respected element then each element will get added and then then it will get divided with sum of weight.

- average(arrey ,weights = weight)

In [ ]:
arr = np.array([1,2,3,4])
weight = np.array([4,3,2,1])

# (1*4 + 2*3 +...+ 4*1 ) / (4+3+2+1)

In [ ]:
np.average(arr, weights = weight) 

2.0

In [76]:
array = np.array ([-10, 0.3, 1.5, 19, -50, -3.5, 11.5, 9])
array

array([-10. ,   0.3,   1.5,  19. , -50. ,  -3.5,  11.5,   9. ])

In [77]:
np.sort(array)

array([-50. , -10. ,  -3.5,   0.3,   1.5,   9. ,  11.5,  19. ])

## argsort( ) --> It will returns us the index.

In [78]:
np.argsort(array)

array([4, 0, 5, 1, 2, 7, 6, 3], dtype=int64)

## sqrt

In [81]:
newarr

array([ 2,  4,  6,  8,  9, 10])

In [82]:
np.sqrt(newarr)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.        ,
       3.16227766])

In [83]:
np.square(newarr)

array([  4,  16,  36,  64,  81, 100])